package main

func GiveError(errorName string) {
	panic(errorName)
}
